HINDSIGHT_DB_PASSWORD: ENC[AES256_GCM,data:FNoAkZ8X,iv:kjtW4p049BzVA4Ns1t90zhcZDKI93CV7ECnqUkwns50=,tag:fnfiZLN2k7G13DBNQn85+A==,type:str]
OPENROUTER_API_KEY: ENC[AES256_GCM,data:e2iX+C/ZT7kJXFB4+dNz8Keh31UxNKPfye7xED+L9vR1dENdtjSdYyAcJa+7yzJppTqgHHEeQAb9VpdBCMmwV+M1GdaMzRSu9A==,iv:Ac0w1kPX+kcl7Xt3nzNnZIA01UHS/kHgFaZeX2ueeNw=,tag:SsMKZf9XXxJ0bNtvBbugvg==,type:str]
GROQ_API_KEY: ENC[AES256_GCM,data:oqQZlIzsX2s558KGl/y+S4E6D8A0ZvN9Ir4cAeL2RK7K5t5fI0IJ/YjVpT94LtS5YlLEiM7dRCg=,iv:4bne3vxn7MEusTIvFqciVWFqJx8130GRs2EbCwmYxAQ=,tag:uf6jBVnNQkdsRHNjQFcAbA==,type:str]
HINDSIGHT_API_TENANT_API_KEY: ENC[AES256_GCM,data:qnNzhK+C+wLWe6GkE6x4it5IGnvY+MzPsQxiwBklSVbb3VeJ4L8ZeV0tMWsskNkfifCQKYBbZHJ/+giuGXkNog==,iv:4RINysde9vS7piQm6HrG9RNWZ4IPlvzHqhTG8P20lCo=,tag:Q6dIUXJ0vsSRR6zzM3yohA==,type:str]
TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:KIo6C2eZgPXdHhBv9RoIU+t578/dGa3MN4ASCLSavmxiGRir+Xolk5JYJoZ0dA==,iv:yD0w6sgX4gtxv71vNKk0qrBWuM8kyVmY1oK1wZK09fw=,tag:6yUu06oAyINpmCZE3i7Hrw==,type:str]
TELEGRAM_CHAT_ID: ENC[AES256_GCM,data:XrmAqAjq+So0Vw==,iv:x8U6RJE0K3on60S8eckyFpeMuAodCd+R2/ki4YrEFbs=,tag:ZGd1XB39+CTRvxINKsInUw==,type:str]
DEOPJIB_DEV_POSTGRES_PASSWORD: ENC[AES256_GCM,data:vQDP7XByyY2sNl7wt6BUOABTK+IVY53J7IgEkkehT3qtd9XuvicEFxISUrEbhmxIef2JGNS6Zt8YpSMS+4oq4w==,iv:z1XUNHIundBEBuyG5awjbB9FpZt2XfqKAHehIDuFYJg=,tag:+sj8Fz5sCZicLhTBlfVwcg==,type:str]
DEOPJIB_DEV_DATABASE_URL: ENC[AES256_GCM,data:by6kZDxJivyLGxLJxfNMaCHsfBu95VWxoM7LEc/MXmck1+yJjAZBrTx9WoIckLJVtfjXbuqa8GgOozf4F8zTgjzDhuzHrS8rEqnX9kSl/TVIOSwR7ZNpnfYgsk8gH3T1eD0C4Nn7I1neWzgdLs7hSC0=,iv:SqIvzxWc44nuu5Ssa5Hgsw5eW/Rgi33GLZm6PH5SbaQ=,tag:+CCiTH6Df9sjnr39DeorRQ==,type:str]
DEOPJIB_DEV_SECRET_KEY_BASE: ENC[AES256_GCM,data:J3Nxc+B/3gJ7/trHsYar/ye+jA75+KqtmPGoRL0/q5g84jca/8hZnC2S+MMoWZGByEiCO3IG0fwfX+MEAgUMrA==,iv:QeDmc628X5H9rBipOIVqg0zI3aW2X9727X3QioM9SMo=,tag:ACmCnfte/KW/adHtZh1NAw==,type:str]
GITHUB_RUNNER_HJ_DOTFILES_TOKEN: ENC[AES256_GCM,data:iLxcIsGht9UIxln6Eh85B9xnq/NfW4GD9tjeZmEVwxMpQzqJw7iBxpTdzCONUhfQ9PBH0hPdLIQqFc0BE4NK8WVzeGPfZhDRxEO4zaOkHTSy+qFj64736pjoQPoF,iv:AxjAyGYdEIy8cHrdBGejQWAL7y0GvQ/xnsmoiCMsTI8=,tag:PLWejGpBsp7fdbU1QKl+VA==,type:str]
sops:
    age:
        - recipient: age14c6z2hf8qr9lumph8smjh7yny25nd7v4xy9guc8n5r2pfrmhjfasrjmhz5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcWphSVVNR1FFOEdkdUUr
            ZkdIUVVBOHBlcFhjbG9NOE0vd2ZuTEZZVmg0CjhnSjg3VlRWbURlS1FoOEZmT01I
            N3R2amdzZmE4TjBXT0VnelFQQjBPZ1UKLS0tIFl1RVFnYWdGdUc4MkRXcUJnMm90
            YXRSVC9uSzloM05JbVFlZVQ5SWxib1kKFa5sCKpwasyJaRV031xEmU4TAaBlW+Pl
            pyEeNYSzGJNlXHNSK4alAFNdbJ9AXg3gydqegCseIq7Wwb3lRQzMoQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13l5ytc0xuqawqzt07xt0gyskk07lyayfsndut3cnyd0slzka7ppq4m3k64
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpdGRlc0VoRnhwSWc3MWtP
            bHU5RTZWRlA4NTdkZnFCVnA3ajQyN1NtaVU4Cmo4UStmbURlS3gxNGJWd2NIeVlS
            Yzd4c1kxSXgrZGZnYUxLNHlSalhzS3cKLS0tIE5pRE9sN2NqOVd1Q2M4NFErdTl4
            L0RJRGUzRzBNMTJDVmJaN1JuN0krbzAK9sK0VgLTNqI0EOh6JtWUnzNbjTc9CWEm
            6HAUZPwoocKdizCce7AvlB1IdJdIqHH+MCjpEI6qCwfotknx9+4Ivw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-21T08:58:44Z"
    mac: ENC[AES256_GCM,data:xaeyuKf8LmHSYy4ARA8FvoP+5OMwbfi1p5uDxHNk6era5o2bgHtEEtrErV2Ggxk3ktMoY/EnBWgBpuxi7Z1Ok3Zw2LcGWN6cfSZjoWAKZ77dGKPUbnHJWXK7ubW+2cmxSs8hG9Ej65ZXU0IHyGP37QQ+eMoZYbi37b4O6I67YW8=,iv:IlKHRIMcIAr0wO0NowT9USgCsLwOvtcBJ0rWps6W2E4=,tag:PgQitOdS7wjhhoIij/ek5g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
