HINDSIGHT_DB_PASSWORD: ENC[AES256_GCM,data:hds3VySI,iv:GcL3roJ6EExmU0hg3Te3oVLPz2nYxj9gnlXY0VIuD5c=,tag:9FXk4dZ4ua3sp+0ELUSvXQ==,type:str]
OPENROUTER_API_KEY: ENC[AES256_GCM,data:bcT6D84JdzanF6DOAmbtGI4nzZNNv29YdSnr6s9qJz5iT0JNo5+gqeq9U4WLqusMnvVveXyEHp6FP3VtXI2qhSIKlHEkYrs9uQ==,iv:GrxsSXlpJ149JT9lSrOFcqp0xbFL60e0SMsKmhSNbf0=,tag:Tgr5mYtvlKj+MGMeb9poIQ==,type:str]
GROQ_API_KEY: ENC[AES256_GCM,data:49GE7SI0UghzCVvwkQf7sJ3fa+wBbIjYR7gzLxNeZ0QZ2kOfixHSsGk/dC3JrpBo27l9iZLOziY=,iv:o8wthSyP13yYOxWUgA8bFNqb/TMANJG4Ano4Pl2/Ul8=,tag:wiuuXOCTHjE2hsH7u8lFiw==,type:str]
HINDSIGHT_API_TENANT_API_KEY: ENC[AES256_GCM,data:6tk/0SAEWQP56rqoTv4pNgXYF1ItoTDmsbqiRzzgqFqME7Dtpn8WsPuePqFiwwF810njT1YbjeCCp9JaN9N9LA==,iv:fOkHXCiSFw/4xJI38vAhKKuuPQrUczY73JvFwfphbVc=,tag:TJmQbBgJB4sHtaBmFHp/FA==,type:str]
sops:
    age:
        - recipient: age14c6z2hf8qr9lumph8smjh7yny25nd7v4xy9guc8n5r2pfrmhjfasrjmhz5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4dUFtakpIcHFsWU9abWJ5
            TE4rcFdvN1U2RHRobVJKeERBTWVINHRVTVRjCkxseWZ0a1Fjb3ZTYXB6anVXdmhQ
            MEhWeUNwNzU4bGxyMkFGbE9tWmFPSm8KLS0tIDN5TloxYnVzRzYrWU10ZVpYY3g4
            SUFNV284TTRjTEVEUVNuOTJQTWgrYjgKlW4O3+m/cuSMpCpxCALd85bSSmpPqwo5
            T/wIB1p/kbR0HYuRnZeaCxrDiWqoKytyCxHXHwoGIYmyBV5IwqfbOw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13l5ytc0xuqawqzt07xt0gyskk07lyayfsndut3cnyd0slzka7ppq4m3k64
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSWnoxbWdiL2JxSlR3MkhF
            M3FSeTBOK1ovS2ltWXVtaXVXYTRSL0NQWGhFCmtZUXM5cEk3NW44MFFzYU8vZVk0
            dFpHeFY5RUVuR01udWVQYm1NMVdjSkEKLS0tIDl3dHhJbWc4U3lpWWNpTnJhWDRP
            WUtFK1hzdEl1S1J2dmVzZ3QvOG93ZVUKaspYZEhWt3SRgYUWKB0NMSI8adzijSgI
            CLATRwvnREMRJq5Y+Z5leRIJ8Dx37quDt8iTA6EcWVtRQau0abXjRg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-15T07:16:54Z"
    mac: ENC[AES256_GCM,data:yd5Z8ecNjIn2LA5lERrpAb4vLRWqQyugJ6bg/rMLQSrB/pQ9gE2LJDNk+ecQL5xmtWoXJak6v+vlNaLEBNeZuoKI2RcGpwwCKIHwi49kb7Ht89cULKIqFsre7k+MaU0EswtLB1t96Sb3BHv7a5Xebwm1yS1cnXuAjDvlqRg3vHM=,iv:FuozXqI0U8qsxQ8ma/08yKbC4WSvK7OZplEP6qNdqgs=,tag:LCEWGjFt4bFf2JVFmrqyLA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
