TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:n9KCcMPoh7MxZ8JE4YcHV2FzgD1l2D3GE5yNxYJtzcwWe6ttuYJutlGyoQyJ2w==,iv:CAprss3sk8HxDDEECxXilNRMmmyl8ILiMEoUe5b1K3g=,tag:UERR6SW8QUNHG1mEzPKlsQ==,type:str]
TELEGRAM_CHAT_ID: ENC[AES256_GCM,data:HRe5MnekzYB5Tg==,iv:tvsCOeBXUrL3EElfqVE5qwUBBV7KSIALGLGRBmcVnzE=,tag:yXSHfs6DxN93oJfTREF5lA==,type:str]
DEOPJIB_DEV_POSTGRES_PASSWORD: ENC[AES256_GCM,data:vQDP7XByyY2sNl7wt6BUOABTK+IVY53J7IgEkkehT3qtd9XuvicEFxISUrEbhmxIef2JGNS6Zt8YpSMS+4oq4w==,iv:z1XUNHIundBEBuyG5awjbB9FpZt2XfqKAHehIDuFYJg=,tag:+sj8Fz5sCZicLhTBlfVwcg==,type:str]
DEOPJIB_DEV_SECRET_KEY_BASE: ENC[AES256_GCM,data:J3Nxc+B/3gJ7/trHsYar/ye+jA75+KqtmPGoRL0/q5g84jca/8hZnC2S+MMoWZGByEiCO3IG0fwfX+MEAgUMrA==,iv:QeDmc628X5H9rBipOIVqg0zI3aW2X9727X3QioM9SMo=,tag:ACmCnfte/KW/adHtZh1NAw==,type:str]
GITHUB_RUNNER_HJ_DOTFILES_TOKEN: ENC[AES256_GCM,data:iLxcIsGht9UIxln6Eh85B9xnq/NfW4GD9tjeZmEVwxMpQzqJw7iBxpTdzCONUhfQ9PBH0hPdLIQqFc0BE4NK8WVzeGPfZhDRxEO4zaOkHTSy+qFj64736pjoQPoF,iv:AxjAyGYdEIy8cHrdBGejQWAL7y0GvQ/xnsmoiCMsTI8=,tag:PLWejGpBsp7fdbU1QKl+VA==,type:str]
NIX_GITHUB_TOKEN: ENC[AES256_GCM,data:aehY1WoOfB0EyhJCDtMhktIwVDwS0yjlxScsFiENuCdIlUG6HBZ5szFkHcIfzXy/3dzX0YNIBrDyWFSrj4U24cwu3KbALqJiJFOOcqGPeGVCs0v+2fhnK+rXqRq3,iv:DvrfZkTG6zgw0lqT2lo8ULj/pXBW1eqWl3T1fUs8HOM=,tag:efPc31yxjsKNzfn5T3TWpg==,type:str]
BACKUP_R2_ACCESS_KEY_ID: ENC[AES256_GCM,data:0EVEkcdnoCTLdaXYCYndsb3E2fU85R0goIy/I6m+jwY=,iv:mRakAm79kU4mNmuGCuSpilQLVq/EvTMxxg1PgLxVS0k=,tag:1ffY7U+vzZBiT4af5NvHXA==,type:str]
BACKUP_R2_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Jj8n2u+4V1vhrVX01nIp084QP+WAhliZ50uoX5S+Lm8nKOmw3Ai/B4oofJ3BuhNEImkFb820o9KsEK3WDF9FcA==,iv:FTUDY1xnOHMNypLOwml7vRHta0w73DEAEmZIwk9TKqo=,tag:xLnVK+oW/v0+mdBdKB02jA==,type:str]
BACKUP_RESTIC_REPOSITORY: ENC[AES256_GCM,data:G62nDJrvoEZyIDKm22zsBg5Oa1lB/FxoDRrXGJkCDynpkDAp1vU6X8OTAPv+vXclJBvOTCZ5UcHt9fkc3z+ab+Q+RI9FgDPRPvpjNV05QkNS15k=,iv:QSFeTty1tjGxyCyXDBGI7nhJ0SLEE+vLnIwV99NTN4A=,tag:HWH3guzgelK0DTcxq9ufhQ==,type:str]
BACKUP_RESTIC_PASSWORD: ENC[AES256_GCM,data:R2Iv7KVVel681+9V9OD7c34//5s1eLESCLA/7BqlE4zXUs3bg+1xSBoinJk=,iv:42oeVSl536Q+ZBwqjEQNOVYPfjyK+iEpoAhuCBzebtI=,tag:kBwz43v1zlyOlkNnwRZ0/g==,type:str]
BESZEL_AGENT_KEY: ENC[AES256_GCM,data:AKKyLG1M09Z/Bk2SnhZkCcROcWmX2dkVPAeBtPwiaR0+XwX/KqQTahUTsOnaQfxFCUp+kM8UPVWkujbQL6ymhb8OAf60TdfHwWHdwti7k1k=,iv:cboVFEHlWvjn6ublhFIXgrAz0GG/5MVKZ321p3xVeNw=,tag:xjRIMvQYIMh5keedtooFBg==,type:str]
BESZEL_AGENT_TOKEN: ENC[AES256_GCM,data:A3PmfGPKPl697vxSD/JR4pGgmXDjRkvJvaimFS2ApeNwa9yn,iv:yA6E9Ulb+sb9WasklTeMjKtw4wcGgPiZOciXx9EtK9A=,tag:cH2Gr2GL/NEGx5e7GdPRuQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcWphSVVNR1FFOEdkdUUr
            ZkdIUVVBOHBlcFhjbG9NOE0vd2ZuTEZZVmg0CjhnSjg3VlRWbURlS1FoOEZmT01I
            N3R2amdzZmE4TjBXT0VnelFQQjBPZ1UKLS0tIFl1RVFnYWdGdUc4MkRXcUJnMm90
            YXRSVC9uSzloM05JbVFlZVQ5SWxib1kKFa5sCKpwasyJaRV031xEmU4TAaBlW+Pl
            pyEeNYSzGJNlXHNSK4alAFNdbJ9AXg3gydqegCseIq7Wwb3lRQzMoQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14c6z2hf8qr9lumph8smjh7yny25nd7v4xy9guc8n5r2pfrmhjfasrjmhz5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpdGRlc0VoRnhwSWc3MWtP
            bHU5RTZWRlA4NTdkZnFCVnA3ajQyN1NtaVU4Cmo4UStmbURlS3gxNGJWd2NIeVlS
            Yzd4c1kxSXgrZGZnYUxLNHlSalhzS3cKLS0tIE5pRE9sN2NqOVd1Q2M4NFErdTl4
            L0RJRGUzRzBNMTJDVmJaN1JuN0krbzAK9sK0VgLTNqI0EOh6JtWUnzNbjTc9CWEm
            6HAUZPwoocKdizCce7AvlB1IdJdIqHH+MCjpEI6qCwfotknx9+4Ivw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13l5ytc0xuqawqzt07xt0gyskk07lyayfsndut3cnyd0slzka7ppq4m3k64
    lastmodified: "2026-08-31T08:13:30Z"
    mac: ENC[AES256_GCM,data:L0fQxeixlzZE5/G+235/51Ngv2yBtyGVvbD4vjSWbvmDRon3gN9e/SycTIaaHgTwSUFTFkcix+K94KjxjT3nEjQi7u9w1CcWcgQYan57opgJagbLdgyri/1BtWVrZE7qjQ51p12E/uL0BYVGDdjbDuUeylbWxzCnYjv7IrOF1yU=,iv:qs2Cd9E2y6+i16K2aKiZ28/5ZuLlRVsAHNhy8+DVAVY=,tag:gw/E1unGQ7A1z2I0HR0hBQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
