keys:
  - &hj_age age14c6z2hf8qr9lumph8smjh7yny25nd7v4xy9guc8n5r2pfrmhjfasrjmhz5

creation_rules:
  # 공통 secrets (모든 사용자가 접근)
  - path_regex: secrets/shared/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          # - *admin_age
          - *hj_age

  # workspace/hj 전용 secrets
  - path_regex: secrets/workspace/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *hj_age
