global_vars:
  - name: currentday
    type: date
    params:
      format: "%Y.%m.%d"

  - name: current_short_day
    type: date
    params:
      format: "%y.%m.%d"

  - name: monthday
    type: date
    params:
      format: "%m.%d"

  - name: currenttime
    type: date
    params:
      format: "%H:%M:%S"

matches:
  - trigger: :date
    replace: "{{currentday}} {{currenttime}}"

  - trigger: :currday
    replace: "{{currentday}}"

  - trigger: :currsday
    replace: "{{current_short_day}}"
