[[language]]
name = "elixir"
language-id = "phoenix-heex"
language-servers = ["tailwind-heex", "elixir-ls", "expert"]
auto-format = true

[[language]]
name = "heex"
language-id = "phoenix-heex"
language-servers = ["tailwind-heex", "elixir-ls", "expert"]
auto-format = true


[language-server.tailwind-heex]
command = "/etc/profiles/per-user/hj/bin/lspmux-mise-tailwindcss-language-server"

[language-server.elixir-ls]
command = "/etc/profiles/per-user/hj/bin/lspmux-mise-elixir-ls"

[language-server.expert]
command = "/etc/profiles/per-user/hj/bin/lspmux-mise-expert"

[[language]]
name = "go"
auto-format = true
language-servers = ["gopls"]

[language-server.gopls]
command = "/etc/profiles/per-user/hj/bin/lspmux-mise-gopls"

[language-server.gopls.config]
usePlaceholders = true
completeUnimported = true
staticcheck = true
semanticTokens = true

[language-server.gopls.config.formatting]
gofumpt = true

[language-server.gopls.config.analyses]
unusedparams = true
unusedwrite = true
shadow = true
nilness = true
useany = true

[language-server.gopls.config.hints]
assignVariableTypes = true
compositeLiteralFields = true
compositeLiteralTypes = true
constantValues = true
functionTypeParameters = true
parameterNames = true
rangeVariableTypes = true

[[language]]
name = "nix"
auto-format = true
language-servers = ["nixd"]

[language-server.nixd]
command = "/etc/profiles/per-user/hj/bin/lspmux-nix-nixd"
