# @generated by usage-cli from add-my-skill

# if "usage" is not installed show an error
if ! type -p usage &> /dev/null
    echo >&2
    echo "Error: usage CLI not found. This is required for completions to work in add-my-skill." >&2
    echo "See https://usage.jdx.dev for more information." >&2
    return 1
end

set _usage_spec_add_my_skill 'name add-my-skill
bin add-my-skill
about "$SKILLIB 디렉토리의 스킬을 Claude Code에 추가"
arg <skill-name> help="추가할 스킬 이름"
complete skill-name run="ls $SKILLIB"
'
set -l tmpdir (if set -q TMPDIR; echo $TMPDIR; else; echo /tmp; end)
set -l spec_file "$tmpdir/usage__usage_spec_add_my_skill.spec"
echo $_usage_spec_add_my_skill > "$spec_file"

set -l tokens
if commandline -x >/dev/null 2>&1
    complete -xc add-my-skill -a "(command usage complete-word --shell fish -f \"$spec_file\" -- (commandline -xpc) (commandline -t))"
else
    complete -xc add-my-skill -a "(command usage complete-word --shell fish -f \"$spec_file\" -- (commandline -opc) (commandline -t))"
end
